export const projects = [
  {
    title: 'SmartCity Data streaming',
    description: "Developed a real-time data streaming pipeline that tracks an entire car journey from London to Birmingham. Utilized a range of tools including IoT devices, Apache Zookeeper, Kafka, Spark, Docker, Python, and AWS services (Glue, Athena, IAM, Redshift) for data ingestion, processing, and storage. Visualized data using PowerBI.",
    image: '/images/1.png',
    tags: ['Apache Zookeeper', 'Kafka', 'Spark', 'AWS', 'IoT','Docker', 'Python'],
    visit: 'https://github.com/AgustinRosarioAX/Real-time-data-streaming-smartcity',
    id: 0,
  },
  {
    title: 'Raspberry-pi-simulation',
    description:"Developed a Raspberry Pi robot simulation in Java. Programmed the robot to capture images of traffic lights within a 30 cm sensor range, process the images to extract RGB values, and perform tasks based on the detected color. Features include path retracing, shape drawing, stunts, and light blinking.",
    image: '/images/2.png',
    tags: ['JAVA'],
    visit: 'https://github.com/AgustinRosarioAX/JAVA-Raspberry-pi-simulation-project',
    id: 1,
  },
  {
    title: 'Stock-Market-Real-Time-Data-Analysis',
    description: "Developed a real-time stock market data pipeline using Kafka and AWS technologies. Implemented data ingestion, processing, and storage solutions utilizing Python, AWS S3, Glue (Crawler and Catalog), EC2, Athena, and SQL.",
      image: '/images/3.png',
      tags: ['Kafka', 'AWS', 'Python'],
    visit: 'https://github.com/AgustinRosarioAX/Stock-Market-Real-Time-Data-Analysis',
    id: 2,
  },
  {
    title: 'Memories - Full Stack App ',
    description: "Built a full stack MERN social media app called 'Memories' using React, Node.js, Express, and MongoDB with full CRUD functionalities. This full-stack MERN application enables users to share and post interesting life events.",
    image: '/images/4.png',
    tags: ['React', 'Node.js', 'Express', 'MongoDB'],
    visit: 'https://github.com/AgustinRosarioAX/Memories',
    id: 3,
  },
  {
    title: 'Stock-Market-Predictor ',
    description: "Developed a Python-based ML model to predict stock market prices using neural networks with TensorFlow and Keras. The model analyzes 10 years of historical data to forecast various moving averages (50-day, 50 vs. 100-day, 100 vs. 200-day) and compare original vs. predicted data. Features include Dense, Dropout, and LSTM layers.",
    image: '/images/5.png',
    tags: ['Machine Learning', 'Neural network', 'TensorFlow', 'Keras'],
    visit: 'https://github.com/AgustinRosarioAX/Stock-Market-Predictor-Python',
    id: 4,
  },
  {
    title: 'Grocery-store-management ',
    description: "Developed a three-tier grocery store management system with Front End using HTML, CSS, JavaScript, and Bootstrap for the backend Python and Flask and for database and data storage MySQL. The application enables admins to create and manage orders and products and perform CRUD (Create, Read, Update, Delete) operations.",
    image: '/images/6.png',
    tags: ['Flask', 'Python', 'MYSQL', 'JavaScript','HTML','CSS'],
    visit: 'https://github.com/AgustinRosarioAX/Grocery-store-management',
    id: 5,
  },
  {
    title: 'Library Management System ',
    description: "Developed a library management system named 'AnnaiIllam Library' using Python and Django. The application integrates with an external API to access thousands of books. Users can buy and return books, while admins have exclusive access to perform CRUD operations for efficient management.",
    image: '/images/7.png',
    tags: ['Django', 'Python', 'HTML'],
    visit: 'https://github.com/AgustinRosarioAX/LibraryInformationManagementSystem',
    id: 6,
  },
  {
    title: 'PyGrocery',
    description: "Built a Grocery app using python Django, which has all the CRUD functionalities",
    image: '/images/8.png',
    tags: ['Django', 'Python', 'HTML'],
    visit: 'https://github.com/AgustinRosarioAX/PythonGroceryApp',
    id: 7,
  },
  {
    title: 'News_Reader_AI ',
    description: "Built an AI-Powered React News Application ,a React-based news application integrated with Alan AI for voice recognition. This app allows users to control and interact with news content using voice commands.",
    image: '/images/9.png',
    tags: ['JavaScript', 'HTML', 'CSS','Alan AI'],
    visit: 'https://github.com/AgustinRosarioAX/News_Reader_AI',
    id: 8,
  },
  {
    title: 'Codex_AI ',
    description: "Created CodexAI, a sophisticated chat application leveraging the GPT-3 API. This app enables users to seek help with JavaScript, React, and other programming languages, translate code between languages, and access a range of advanced AI-driven programming assistance.",
    image: '/images/10.png',
    tags: ['JavaScript', 'CSS', 'HTML','GPT3'],
    visit: 'https://github.com/AgustinRosarioAX/codex_ai',
    id: 9,
  },
  {
    title: 'Excel-Automation ',
    description: "Developed an Excel automation solution using Python and Jupyter Notebook, capable of processing millions of data entries within seconds.",
    image: '/images/11.png',
    tags: ['Python', 'Jupyter Notebook'],
    visit: 'https://github.com/AgustinRosarioAX/Excel-Automation-python',
    id: 10,
  },
 
];

export const TimeLineData = [
  { year: 2017, text: 'Started my journey', },
  { year: 2018, text: 'Worked as a freelance developer', },
  { year: 2019, text: 'Founded JavaScript Mastery', },
  { year: 2020, text: 'Shared my projects with the world', },
  { year: 2021, text: 'Started my own platform', },
];